### PR TITLE
Fix OutOfMemory in read stream

### PR DESCRIPTION
**Pull request by medvedev1088**
Fix for https://github.com/ethereumjs/merkle-patricia-tree/issues/36

The root cause of the issue is the trie is traversed asynchronously, in such a way that nodes on different levels are explored with equal probability, resembling breadth-first search. This requires the bulk of the trie to be loaded into memory before any entries can be emitted by the stream.

This pull request adds `PrioritizedTaskExecutor` with a pool and a priority queue, node lookups are prioritised by node key length. This resembles depth-first search, which solves the issue.

Also tested here https://github.com/medvedev1088/merkle-patricia-tree/pull/1

New code is covered in `test/prioritizedTaskExecutor.js` but coverage only picks `test/index.js`

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi, great, thanks for this extensive PR! 😺

I will try to have a look into this next week, currently at EthCC (if you are as well we can also meet).

Can you rebase and squash the first 7 commits (be7ae to eece4) into the first (be7ae) commit, and also squash together the last two commits, these are mostly back-and-forth commits and bloat the commit history (if you haven't use rebase functionality before you should do a local copy of your repository directory since things can go wrong).

**Comment by holgerd77** [comment]
Process would be: update your ``master`` branch with the latest ``master`` changes, go to your branch and do ``git rebase -i master``.

**Comment by medvedev1088** [comment]
@holgerd77 Done!

Unfortunately, I'm not at EthCC.

**Comment by holgerd77** [comment]
Beautiful. 👍 

Otherwise this is ready for review?

**Comment by medvedev1088** [comment]
Yep, ready :)

**Comment by holgerd77** [comment]
Just did the associated release on npm: https://github.com/ethereumjs/merkle-patricia-tree/releases/tag/v2.3.1

**Pull request merged**
