### PR TITLE
Promisify proof generation and verification

### PR DESCRIPTION
**Pull request by s1na**
This is the start of the promisification effort. It promisifies the static methods for generating proofs and verifying them and modifies the tests to use  async/await syntax.

I'm thinking about changing the return types a bit to make them more suitable for promises. To give an example `findPath` has a callback with signature `(err: Error, node: TrieNode, remaining: number[], stack: TrieNode[])`. I'd like to define an interface `interface Path { node: TrieNode, remaining: number[], stack: TrieNode[] }`, which the promisified `findPath` returns.

### CODE REVIEW

**Comment by s1na** [comment]
Build failed because node v6 doesn't support the async/await syntax. Dropped node v6 in travis and added v11 and v12 to be consistent with other libs (e.g. util).

**Comment by holgerd77** [comment]
Hi Sina @s1na, Ryan @ryanio is now on the road to continue with the promisification efforts. 😄 Can you take some in-between time and do a short rebase here so that we can get this merged as some basis for further efforts?

That would be great!

**Comment by ryanio** [comment]
PR changes were really easy and straight-forward to follow along, thanks @s1na. This branch is now up to date.

> I'm thinking about changing the return types a bit to make them more suitable for promises. 

This is a great idea, I'll continue on this effort tomorrow.

**Comment by s1na** [comment]
Oh sorry for the delay, I wanted to get started on this today. Thanks for taking initiative yourself @ryanio!

**Comment by holgerd77** [comment]
@ryanio Eventually directly do the review here and merge and then do the follow-up work in a new PR. Then the changes here are already reviewed and further review process is relieved a bit.

**Comment by ryanio** [comment]
@holgerd77 @s1na ok great thanks, branch is ready to be merged, can one of you give an approval?

**Comment by holgerd77** [comment]
@ryanio ah, thought you could do yourself since Sina initiated the PR? Anyhow, will approve.

**Comment by holgerd77** [comment]
(fee free to merge)

**Pull request merged**
