### PR TITLE
merkle proof

### PR DESCRIPTION
**Pull request by jbaylina**
Implementation of merkle proofs.

Tries to follow the same pattern that the ones used in go-ethereum in the thin-client implementation.

### CODE REVIEW

**Comment by jbaylina** [comment]
In order for the tests to pass, PR14 must be applied first
https://github.com/ethereumjs/merkle-patricia-tree/pull/14

**Comment by holgerd77** [comment]
This is such an extensive and beautiful PR, what a pity that it went unattended for so long. Any reasons not to merge this (after some review)?

**Comment by cdetrio** [comment]
@holgerd77 I've been working on something (a merkle trie/proof visualization thing) and this is exactly what I need. 👍

**Comment by holgerd77** [comment]
@cdetrio Ah, cool, I actually googled for some visualization possibility when looking into this for the first time, would be pretty useful! :-)

Will do a more thorough review of this PR on Monday and then (probably) merge, since on first glance this makes a very solid impression.

**Comment by holgerd77** [comment]
(@jbaylina thanks for this PR on this occasion, sorry that there was no earlier reaction. We have the general problem here in ``ethereumjs`` that we have every now-and-then libraries where old contributors are moving on no one feels really responsible for some time)

**Comment by jbaylina** [comment]
Great! I think this is important for the light client.  FYI They were "copied" from the geth client.

As you can imagine I do not have the code fresh in my head! :) But if you have any doubt, plesse let me know!

**Comment by holgerd77** [comment]
@jbaylina Hey, do you still have the resources in place to rebase so that the tests can (hopefully :-)) pass? The ``_findPath`` method also has been renamed to a public ``findPath``, that would also have to be changed.

If it's not possible, I can also do it via re-adding the branch directly to the repo and do a new PR from there.

**Comment by holgerd77** [comment]
@jbaylina And - yes! - this would be really great for the light client! :-)

**Comment by holgerd77** [comment]
@jbaylina you didn't rebase against the latest status of the original master branch, that's why all the old commits are included as well. You have to first [add the original repository as an upstream](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) (if you haven't already). Then you can go to your PR branch and do the rebase against ``upstream/master`` (or the updated local ``master``).

Not sure, if you can do this again now from the current state, maybe try. But I would highly recommend to do a local copy of the whole repository before. Rebasing is a very hairy process - especially if you start with this - I've gone through this process already not that long time ago. :-)

**Comment by holgerd77** [comment]
@jbaylina "...add as an upstream" and also update your local master branch.

**Comment by holgerd77** [comment]
Oh, cool, that looks a lot better now! :-)

**Pull request merged**
