### PR TITLE
return stack for merkle proof

### PR DESCRIPTION
**Pull request by zmitton**
This is a very easy way to enable the extraction of merkleproof data from this js module. Literally a one-line change. It does not break the existing API and only passes a reference (so no performance decreases either).

This data has everything needed to make the merkleproof (although it may be useful to reformat it into a standard like open-timestamp or chainpoint). I am creating a module to do the rest of the work and verify the proofs. Happy to merge it in this repo as well (if you want).

### CODE REVIEW

**Comment by wanderer** [comment]
Looks good to me. @kumavis any comments here?

**Comment by kumavis** [comment]
I think this PR is ok but better to make findPath public
things like `remainder` are useful to return as well

**Comment by kumavis** [comment]
also i realized today that the diff in this PR while it looks like a non-breaking change, it would break if this were being used in an async.waterfall (different number of results -> different args to following method)

**Comment by zmitton** [comment]
closing because fixed by PR #22

**Pull request closed without merging**
