### PR TITLE
Drop ethereumjs-testing dep and fix bug in branch value update

### LINKED ISSUE #54: Library fails branch-value-update test
Upstream in the official tests, a new test "branch-value-update" was added:

```json
  "branch-value-update": {
    "in": [
      [ "abc", "123" ],
      [ "abcd", "abcd" ],
      [ "abc", "abc" ]
    ],
    "root": "0x7a320748f780ad9ad5b0837302075ce0eeba6c26e3d8562c67ccc0f1b273298a"
  }
```

This library fails that test. In particular, it seems that search stops at an extension node when it should check the value in the branch node.

### PR DESCRIPTION
**Pull request by s1na**
This PR upgrades drops `ethereumjs-testing` dependency, adds the test fixture files directly to the repository and fixes #54 which caused a new test case to fail.

### CODE REVIEW

**Comment by holgerd77** [comment]
Will do an `ethereumjs-testing` update in a minute 😄 together with a `v1.2.6` release. If you want you can directly upgrade to this. Shouldn't have any effect though since trie tests very likely haven't been touched, so would be only for the "optics". 😛

**Comment by s1na** [comment]
@holgerd77 Sure, we might as well upgrade to the latest version :)

Browsers tests are now failing. It seems `ethereumjs-testing` depends on `asyncawait` which depends on `node-fibers` which doesn't work in browsers! Searching more to see if there's a workaround.

**Comment by s1na** [comment]
@holgerd77 Even without the `asyncawait` issue karma isn't able to find the json test files from `ethereumjs-testing`. Do you have any ideas? Do other projects run `ethereumjs-testing` tests also in browser?

**Comment by holgerd77** [comment]
Hmm, not sure. @danjm is also working on a tests update https://github.com/ethereumjs/ethereumjs-tx/pull/131 on the tx library and this library also has a browser test configuration and script. However the test run is deactivated in [.travis.yml](https://github.com/ethereumjs/ethereumjs-tx/blob/master/.travis.yml) (which also shouldn't be the case, don't know the reasoning ad hoc).

Maybe the PR from Dan helps nevertheless, eventually you can check it out and see if the browser tests pass manually? Otherwise you can figure out together?

**Comment by holgerd77** [comment]
One other thing for consideration: these trie tests here are also pretty static, there was just one test case added in the last four years or so. Maybe we should also follow the path here to just remove this dependency all together like being done in https://github.com/ethereumjs/ethereumjs-block/pull/61 for the block library (together with some copying and wrapping - see block PR-related issue - on the test files).

The `tests` dependency is a super-heavy several hundred MBs dependency which takes ages on installation, think this would very much make sense here too, think trie tests are just some KB compared.

**Comment by s1na** [comment]
@holgerd77 Took you on your offer :smile: Added the json test files directly to the repository and dropped `ethereumjs-testing` dependency. Tests are passing now.

**Comment by holgerd77** [comment]
Ah, but could you add the wrapping of the file structures with some meta fields for file information as well, see https://github.com/ethereumjs/ethereumjs-block/issues/55 for reference.

**Comment by s1na** [comment]
Ah, I had missed that. Added the metadata.

**Pull request merged**
